server:
  port: 10015
spring:
  application:
    name: comsumernote-consumer
  boot:
    admin:
      client:
        url: http://localhost:8000
  profiles:
    include: devtool
eureka:
  client:
    allow-redirects: false
    fetch-registry: true
    enabled: true
    service-url:
      defaultZone: http://localhost:8001/eureka/