server:
  port: 8888
spring:
  boot:
    admin:
      client:
        url: http://localhost:8000
  application:
    name: configServer
  cloud:
    config:
      server:
        bootstrap: true
  profiles:
    active: native
#是否需要拉取服务信息，默认未true       fetchRegistry等同于 fetch-registry
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false