server:
  port: 9002
spring:
  application:
    name: codemaker
  boot:
    admin:
      client:
        url: http://localhost:8000
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java #重启目录
code:
  maker:
    datasource:
      url:  jdbc:sqlite:E:\sqlite\data\captcha.db
      drivername: org.sqlite.JDBC
      vender: sqlite
    architec:
      controllerpck: controller
      servicepck: service
      daosuffix: mapper
      domainpck: domain
      orm-type: mybatisplus
    project:
      author: zhengzz
      name: demo
      modulename: com.zzz.hathor
      desc: demo
      permitlombok: false
mybatis:
  mapper-locations: classpath:com/zzz/hathor/codemaker/mapper/*.xml

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka/
    fetch-registry: true
ribbon:
  eureka:
    enabled: true
