server:
  port: 8005
spring:
  boot:
    admin:
      client:
        url: http://localhost:8000
  application:
    name: configclient
  cloud:
    config:
      name: configtest
      discovery:
        enabled: true
#是否需要拉取服务信息，默认未true       fetchRegistry等同于 fetch-registry
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
