eureka:
  client:
    healthcheck:
      enabled: true
    allow-redirects: false
    fetch-registry: true
    enabled: true
    service-url:
      defaultZone: http://localhost:8001/eureka/
spring:
  boot:
    admin:
      client:
        enabled: true
        url: http://localhost:8000
zuul:
  routes:
    apia:
      path: /coder/**
      serviceId: codermaker