server:
  port: 10010
spring:
  application:
    name: comsumernote-provider
  boot:
    admin:
      client:
        url: http://localhost:8000
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
  profiles:
    include: devtool

eureka:
  client:
    allow-redirects: false
    fetch-registry: true
    enabled: true
    service-url:
      defaultZone: http://localhost:8001/eureka/