spring:
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
      poll-interval: 1s
      quiet-period: 400ms
      additional-paths: src/main/java
    remote:
      restart:
        enabled: true