server:
  port: 8006
spring:
  redis:
    database: 0
    host: localhost
    port: 6380
    timeout: 10000
    lettuce:
      cluster:
        refresh:
          adaptive: false
      pool:
        max-active: 8
        max-idle: 8
        max-wait: 100ms
        min-idle: 2
      shutdown-timeout: 100ms
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:E:\sqlite\data\captcha.db
  messages:
    basename: static/i18n/messages
mybatis-plus:
  mapper-locations: classpath*:/com/zzz/hathor/captcha/mapper/**/*.xml
  config-location: classpath:/mybatis-config.xml
#是否需要拉取服务信息，默认未true       fetchRegistry等同于 fetch-registry
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false