server:
  port: 8007
spring:
  redis:
    database: 0
    host: localhost
    port: 6380
    timeout: 10000
    lettuce:
      cluster:
        refresh:
          adaptive: false
      pool:
        max-active: 8
        max-idle: 8
        max-wait: 100ms
        min-idle: 2
      shutdown-timeout: 100ms
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false